# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.0.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(258, 365)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.imgpathDisplay = QLineEdit(self.centralwidget)
        self.imgpathDisplay.setObjectName(u"imgpathDisplay")
        self.imgpathDisplay.setGeometry(QRect(8, 21, 123, 19))
        self.imgpathDisplay.setReadOnly(True)
        self.imgpathButton = QPushButton(self.centralwidget)
        self.imgpathButton.setObjectName(u"imgpathButton")
        self.imgpathButton.setGeometry(QRect(129, 20, 73, 21))
        self.processButton = QPushButton(self.centralwidget)
        self.processButton.setObjectName(u"processButton")
        self.processButton.setGeometry(QRect(10, 250, 75, 22))
        self.MosaicColsVal = QSpinBox(self.centralwidget)
        self.MosaicColsVal.setObjectName(u"MosaicColsVal")
        self.MosaicColsVal.setGeometry(QRect(10, 150, 42, 21))
        self.MosaicColsVal.setMinimum(1)
        self.MosaicColsVal.setSingleStep(1)
        self.MosaicColsVal.setValue(4)
        self.MosaicColsLabel = QLabel(self.centralwidget)
        self.MosaicColsLabel.setObjectName(u"MosaicColsLabel")
        self.MosaicColsLabel.setGeometry(QRect(60, 150, 71, 20))
        self.rangeLabel = QLabel(self.centralwidget)
        self.rangeLabel.setObjectName(u"rangeLabel")
        self.rangeLabel.setGeometry(QRect(75, 70, 51, 20))
        self.rangeStartVal = QLineEdit(self.centralwidget)
        self.rangeStartVal.setObjectName(u"rangeStartVal")
        self.rangeStartVal.setGeometry(QRect(10, 70, 30, 19))
        self.rangeEndVal = QLineEdit(self.centralwidget)
        self.rangeEndVal.setObjectName(u"rangeEndVal")
        self.rangeEndVal.setGeometry(QRect(160, 70, 41, 19))
        self.savepathButton = QPushButton(self.centralwidget)
        self.savepathButton.setObjectName(u"savepathButton")
        self.savepathButton.setGeometry(QRect(131, 209, 71, 21))
        self.savepathDisplay = QLineEdit(self.centralwidget)
        self.savepathDisplay.setObjectName(u"savepathDisplay")
        self.savepathDisplay.setGeometry(QRect(10, 210, 123, 19))
        self.savepathDisplay.setReadOnly(True)
        self.saveName = QLineEdit(self.centralwidget)
        self.saveName.setObjectName(u"saveName")
        self.saveName.setGeometry(QRect(10, 188, 121, 19))
        self.saveName.setMaxLength(16)
        self.rangeStartLabel = QLabel(self.centralwidget)
        self.rangeStartLabel.setObjectName(u"rangeStartLabel")
        self.rangeStartLabel.setGeometry(QRect(45, 70, 31, 20))
        self.rangeStartLabel.setAlignment(Qt.AlignCenter)
        self.rangeEndLabel = QLabel(self.centralwidget)
        self.rangeEndLabel.setObjectName(u"rangeEndLabel")
        self.rangeEndLabel.setGeometry(QRect(125, 70, 31, 20))
        self.rangeEndLabel.setAlignment(Qt.AlignCenter)
        self.imageSelectLabel = QLabel(self.centralwidget)
        self.imageSelectLabel.setObjectName(u"imageSelectLabel")
        self.imageSelectLabel.setGeometry(QRect(10, 0, 190, 20))
        self.rangeCountLabel = QLabel(self.centralwidget)
        self.rangeCountLabel.setObjectName(u"rangeCountLabel")
        self.rangeCountLabel.setGeometry(QRect(10, 90, 71, 20))
        self.calcTotalSizeLabel = QLabel(self.centralwidget)
        self.calcTotalSizeLabel.setObjectName(u"calcTotalSizeLabel")
        self.calcTotalSizeLabel.setGeometry(QRect(10, 110, 71, 20))
        self.WXH_Label = QLabel(self.centralwidget)
        self.WXH_Label.setObjectName(u"WXH_Label")
        self.WXH_Label.setGeometry(QRect(10, 40, 71, 20))
        self.calcTotalSizeLabelDisplay = QLabel(self.centralwidget)
        self.calcTotalSizeLabelDisplay.setObjectName(u"calcTotalSizeLabelDisplay")
        self.calcTotalSizeLabelDisplay.setGeometry(QRect(80, 110, 70, 20))
        self.rangeCountLabelDisplay = QLabel(self.centralwidget)
        self.rangeCountLabelDisplay.setObjectName(u"rangeCountLabelDisplay")
        self.rangeCountLabelDisplay.setGeometry(QRect(80, 90, 70, 20))
        self.WXH_LabelDisplay = QLabel(self.centralwidget)
        self.WXH_LabelDisplay.setObjectName(u"WXH_LabelDisplay")
        self.WXH_LabelDisplay.setGeometry(QRect(80, 40, 71, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.imgpathDisplay.raise_()
        self.imgpathButton.raise_()
        self.processButton.raise_()
        self.MosaicColsVal.raise_()
        self.MosaicColsLabel.raise_()
        self.rangeLabel.raise_()
        self.rangeStartVal.raise_()
        self.savepathButton.raise_()
        self.savepathDisplay.raise_()
        self.saveName.raise_()
        self.rangeStartLabel.raise_()
        self.rangeEndLabel.raise_()
        self.imageSelectLabel.raise_()
        self.rangeCountLabel.raise_()
        self.calcTotalSizeLabel.raise_()
        self.WXH_Label.raise_()
        self.rangeEndVal.raise_()
        self.calcTotalSizeLabelDisplay.raise_()
        self.rangeCountLabelDisplay.raise_()
        self.WXH_LabelDisplay.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 258, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.imgpathButton, self.rangeStartVal)
        QWidget.setTabOrder(self.rangeStartVal, self.rangeEndVal)
        QWidget.setTabOrder(self.rangeEndVal, self.MosaicColsVal)
        QWidget.setTabOrder(self.MosaicColsVal, self.savepathButton)
        QWidget.setTabOrder(self.savepathButton, self.processButton)
        QWidget.setTabOrder(self.processButton, self.savepathDisplay)
        QWidget.setTabOrder(self.savepathDisplay, self.imgpathDisplay)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ImageTiler", None))
        self.imgpathDisplay.setPlaceholderText(QCoreApplication.translate("MainWindow", u"image sequence path", None))
        self.imgpathButton.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.processButton.setText(QCoreApplication.translate("MainWindow", u"Process", None))
        self.MosaicColsLabel.setText(QCoreApplication.translate("MainWindow", u"Mosaic Cols", None))
        self.rangeLabel.setText(QCoreApplication.translate("MainWindow", u"<RANGE>", None))
        self.rangeStartVal.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.rangeEndVal.setPlaceholderText(QCoreApplication.translate("MainWindow", u"1", None))
        self.savepathButton.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.savepathDisplay.setPlaceholderText(QCoreApplication.translate("MainWindow", u"save folder", None))
        self.saveName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"save as name", None))
        self.rangeStartLabel.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.rangeEndLabel.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.imageSelectLabel.setText(QCoreApplication.translate("MainWindow", u"Select Image in Sequence", None))
        self.rangeCountLabel.setText(QCoreApplication.translate("MainWindow", u"COUNT", None))
        self.calcTotalSizeLabel.setText(QCoreApplication.translate("MainWindow", u"TOTAL SIZE", None))
        self.WXH_Label.setText(QCoreApplication.translate("MainWindow", u"W x H", None))
        self.calcTotalSizeLabelDisplay.setText(QCoreApplication.translate("MainWindow", u"TOTAL SIZE", None))
        self.rangeCountLabelDisplay.setText(QCoreApplication.translate("MainWindow", u"COUNT", None))
        self.WXH_LabelDisplay.setText(QCoreApplication.translate("MainWindow", u"W x H", None))
    # retranslateUi

