# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created: Tue Feb 21 16:26:59 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(258, 365)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgpathDisplay = QtGui.QLineEdit(self.centralwidget)
        self.imgpathDisplay.setGeometry(QtCore.QRect(8, 21, 123, 19))
        self.imgpathDisplay.setReadOnly(True)
        self.imgpathDisplay.setObjectName("imgpathDisplay")
        self.imgpathButton = QtGui.QPushButton(self.centralwidget)
        self.imgpathButton.setGeometry(QtCore.QRect(129, 20, 73, 21))
        self.imgpathButton.setObjectName("imgpathButton")
        self.processButton = QtGui.QPushButton(self.centralwidget)
        self.processButton.setGeometry(QtCore.QRect(10, 250, 75, 22))
        self.processButton.setObjectName("processButton")
        self.MosaicColsVal = QtGui.QSpinBox(self.centralwidget)
        self.MosaicColsVal.setGeometry(QtCore.QRect(10, 150, 42, 21))
        self.MosaicColsVal.setMinimum(1)
        self.MosaicColsVal.setSingleStep(1)
        self.MosaicColsVal.setProperty("value", 4)
        self.MosaicColsVal.setObjectName("MosaicColsVal")
        self.MosaicColsLabel = QtGui.QLabel(self.centralwidget)
        self.MosaicColsLabel.setGeometry(QtCore.QRect(60, 150, 71, 20))
        self.MosaicColsLabel.setObjectName("MosaicColsLabel")
        self.rangeLabel = QtGui.QLabel(self.centralwidget)
        self.rangeLabel.setGeometry(QtCore.QRect(75, 70, 51, 20))
        self.rangeLabel.setObjectName("rangeLabel")
        self.rangeStartVal = QtGui.QLineEdit(self.centralwidget)
        self.rangeStartVal.setGeometry(QtCore.QRect(10, 70, 30, 19))
        self.rangeStartVal.setObjectName("rangeStartVal")
        self.rangeEndVal = QtGui.QLineEdit(self.centralwidget)
        self.rangeEndVal.setGeometry(QtCore.QRect(160, 70, 41, 19))
        self.rangeEndVal.setObjectName("rangeEndVal")
        self.savepathButton = QtGui.QPushButton(self.centralwidget)
        self.savepathButton.setGeometry(QtCore.QRect(131, 209, 71, 21))
        self.savepathButton.setObjectName("savepathButton")
        self.savepathDisplay = QtGui.QLineEdit(self.centralwidget)
        self.savepathDisplay.setGeometry(QtCore.QRect(10, 210, 123, 19))
        self.savepathDisplay.setReadOnly(True)
        self.savepathDisplay.setObjectName("savepathDisplay")
        self.saveName = QtGui.QLineEdit(self.centralwidget)
        self.saveName.setGeometry(QtCore.QRect(10, 188, 121, 19))
        self.saveName.setMaxLength(16)
        self.saveName.setObjectName("saveName")
        self.rangeStartLabel = QtGui.QLabel(self.centralwidget)
        self.rangeStartLabel.setGeometry(QtCore.QRect(45, 70, 31, 20))
        self.rangeStartLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rangeStartLabel.setObjectName("rangeStartLabel")
        self.rangeEndLabel = QtGui.QLabel(self.centralwidget)
        self.rangeEndLabel.setGeometry(QtCore.QRect(125, 70, 31, 20))
        self.rangeEndLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.rangeEndLabel.setObjectName("rangeEndLabel")
        self.imageSelectLabel = QtGui.QLabel(self.centralwidget)
        self.imageSelectLabel.setGeometry(QtCore.QRect(10, 0, 190, 20))
        self.imageSelectLabel.setObjectName("imageSelectLabel")
        self.rangeCountLabel = QtGui.QLabel(self.centralwidget)
        self.rangeCountLabel.setGeometry(QtCore.QRect(10, 90, 71, 20))
        self.rangeCountLabel.setObjectName("rangeCountLabel")
        self.calcTotalSizeLabel = QtGui.QLabel(self.centralwidget)
        self.calcTotalSizeLabel.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.calcTotalSizeLabel.setObjectName("calcTotalSizeLabel")
        self.WXH_Label = QtGui.QLabel(self.centralwidget)
        self.WXH_Label.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.WXH_Label.setObjectName("WXH_Label")
        self.calcTotalSizeLabelDisplay = QtGui.QLabel(self.centralwidget)
        self.calcTotalSizeLabelDisplay.setGeometry(QtCore.QRect(80, 110, 70, 20))
        self.calcTotalSizeLabelDisplay.setObjectName("calcTotalSizeLabelDisplay")
        self.rangeCountLabelDisplay = QtGui.QLabel(self.centralwidget)
        self.rangeCountLabelDisplay.setGeometry(QtCore.QRect(80, 90, 70, 20))
        self.rangeCountLabelDisplay.setObjectName("rangeCountLabelDisplay")
        self.WXH_LabelDisplay = QtGui.QLabel(self.centralwidget)
        self.WXH_LabelDisplay.setGeometry(QtCore.QRect(80, 40, 71, 20))
        self.WXH_LabelDisplay.setObjectName("WXH_LabelDisplay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 258, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.imgpathButton, self.rangeStartVal)
        MainWindow.setTabOrder(self.rangeStartVal, self.rangeEndVal)
        MainWindow.setTabOrder(self.rangeEndVal, self.MosaicColsVal)
        MainWindow.setTabOrder(self.MosaicColsVal, self.savepathButton)
        MainWindow.setTabOrder(self.savepathButton, self.processButton)
        MainWindow.setTabOrder(self.processButton, self.savepathDisplay)
        MainWindow.setTabOrder(self.savepathDisplay, self.imgpathDisplay)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ImageTiler", None, QtGui.QApplication.UnicodeUTF8))
        self.imgpathDisplay.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "image sequence path", None, QtGui.QApplication.UnicodeUTF8))
        self.imgpathButton.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.processButton.setText(QtGui.QApplication.translate("MainWindow", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.MosaicColsLabel.setText(QtGui.QApplication.translate("MainWindow", "Mosaic Cols", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeLabel.setText(QtGui.QApplication.translate("MainWindow", "<RANGE>", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeStartVal.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeEndVal.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.savepathButton.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.savepathDisplay.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "save folder", None, QtGui.QApplication.UnicodeUTF8))
        self.saveName.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "save as name", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeStartLabel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeEndLabel.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSelectLabel.setText(QtGui.QApplication.translate("MainWindow", "Select Image in Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeCountLabel.setText(QtGui.QApplication.translate("MainWindow", "COUNT", None, QtGui.QApplication.UnicodeUTF8))
        self.calcTotalSizeLabel.setText(QtGui.QApplication.translate("MainWindow", "TOTAL SIZE", None, QtGui.QApplication.UnicodeUTF8))
        self.WXH_Label.setText(QtGui.QApplication.translate("MainWindow", "W x H", None, QtGui.QApplication.UnicodeUTF8))
        self.calcTotalSizeLabelDisplay.setText(QtGui.QApplication.translate("MainWindow", "TOTAL SIZE", None, QtGui.QApplication.UnicodeUTF8))
        self.rangeCountLabelDisplay.setText(QtGui.QApplication.translate("MainWindow", "COUNT", None, QtGui.QApplication.UnicodeUTF8))
        self.WXH_LabelDisplay.setText(QtGui.QApplication.translate("MainWindow", "W x H", None, QtGui.QApplication.UnicodeUTF8))

